### ISSUE TITLE
Kanban-Board Setup

### ISSUE THREAD

**Issue by Doheera-kosi** [Doheera-kosi/Food-Palace#21]
### The activities below were achieved in this milestone:

- Created an empty repository for our group project.
- Followed the steps described in [curriculum-tools-copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects).
- Opened a GitHub project (Kanban board) in our team repo.
- Made sure that in the card titles you can see: Student A, and Student B
- Made sure that each card starts with [Xpt] - that number indicates the number of points that shows how complex the task is. 1 point = 1 hour of work.
- Removed all cards with Student C in the title since we're only two in the team
- Decided who in our team is the Student A, and Student B.
- We assigned ourselves to the correct cards. Decided who will be the assignee for the cards marked as group tasks. All cards on your Kanban board should have assignees.

## Note:
- [x] This team is made up of two members

### [Issue Link](https://github.com/Doheera-kosi/kanban-board/issues/21)

**Comment by nedjwab** [comment]
# 🟢 Project Approved! 🏆

## Hi @team  👋

Your project is complete! ✔️ 🏁

Your code was very professional 💯

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉

 
## Highlights 🌟

- ✔️ nice implementing the kanban board.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by teke85** [comment]
This task is complete
